@startwbs

* Gerencia
** Compras
*** Administración de Proveedores
*** Administración de Depósito
** Comercialización
*** Ventas
*** Empaque
** Administración
*** RRHH
*** Marketing
*** Payroll

@endwbs