@startwbs

* Gerencia
** Compras
*** Administración de Proveedores
*** Administración de Deposito
** Comercialización
*** Ventas
*** Empaque
** Administración
*** RRHH
*** Marketing
*** Payrol

@endwbs